baseurl: "/physalia-workshop"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-font-awesome-sass

font-awesome:
  assets: true

sass:
    load_paths:
        - _sass
        - node_modules

include: ["_pages", "_pages/labs"]
exclude: []          
